const roleData={
 student:{label:"Student / Library Member",home:"dashboard.html",avatar:"AR",name:"Ananya Rao",nav:[["dashboard.html","⌂","Dashboard"],["catalog.html","▣","Book Catalogue"],["digital.html","▤","Digital Library"],["circulation.html","↻","My Books & Loans"],["reservations.html","📌","Reservations"],["rules.html","▤","Library Rules"],["profile.html","◉","My Profile"],["help.html","?","Help Desk"]]},
 librarian:{label:"Librarian Staff",home:"librarian-dashboard.html",avatar:"PL",name:"P. Lakshmi Devi",nav:[["librarian-dashboard.html","⌂","Dashboard"],["issue.html","＋","Issue Book"],["return.html","↩","Return Book"],["renew.html","↻","Renew Loans"],["librarian-catalogue.html","▣","Catalogue Search"],["members.html","♙","Member Lookup"],["notices.html","!","Library Notices"],["librarian-profile.html","◉","Staff Profile"]]},
 admin:{label:"Administrator",home:"admin.html",avatar:"SR",name:"Dr. S. Ramachandra Reddy",nav:[["admin.html","⌂","Admin Dashboard"],["catalogue-management.html","▣","Catalogue Inventory"],["digital-resource-management.html","▤","Digital Resources"],["members.html","♙","Members Directory"],["reports.html","▥","Reports & Audit"],["role-auth.html","✓","IAM Role Verifier"],["notices.html","!","Publish Notices"],["admin-profile.html","◉","Admin Profile"]]}
};
const access={
 student:new Set(["dashboard.html","catalog.html","digital.html","circulation.html","reservations.html","rules.html","profile.html","help.html","book-details.html","notices.html","about.html","contact.html","terms.html"]),
 librarian:new Set(["librarian-dashboard.html","issue.html","return.html","renew.html","librarian-catalogue.html","members.html","notices.html","librarian-profile.html","catalog.html","digital.html","book-details.html","rules.html","help.html","about.html","contact.html","terms.html"]),
 admin:new Set(["admin.html","catalogue-management.html","digital-resource-management.html","members.html","reports.html","role-auth.html","notices.html","admin-profile.html","catalog.html","digital.html","book-details.html","rules.html","help.html","about.html","contact.html","terms.html"])
};
function getRole(){return sessionStorage.getItem("libraryRole")||null}
function setRole(r){sessionStorage.setItem("libraryRole",r)}
function currentPage(){return location.pathname.split("/").pop()||"index.html"}
function guardRoute(){const page=currentPage();if(["index.html","login.html","unauthenticated.html","launcher.html"].includes(page))return true;const role=getRole();if(!role||!access[role]||!access[role].has(page)){location.replace("unauthenticated.html?from="+encodeURIComponent(page));return false}return true}
function logout(e){if(e)e.preventDefault();sessionStorage.removeItem("libraryRole");location.href="../index.html"}
function renderSidebar(){const el=document.getElementById("sidebar");if(!el)return;const role=getRole(),d=roleData[role],cur=currentPage();if(!d)return;el.innerHTML=`<div class="brand"><div class="brand-mark">G</div><div class="brand-text">GLA <span>e-Library</span></div></div><div class="nav-label">${d.label.toUpperCase()}</div>${d.nav.map(n=>`<a class="nav-link ${cur===n[0]?"active":""}" href="${n[0]}"><span class="nav-icon">${n[1]}</span>${n[2]}</a>`).join("")}<div class="nav-label">LIBRARY SERVICES</div><a class="nav-link" href="catalog.html"><span class="nav-icon">⌕</span>${role==="student"?"Search Catalogue":"Public Catalogue"}</a><a class="nav-link" href="digital.html"><span class="nav-icon">◫</span>Digital Repository</a><div class="sidebar-bottom"><a class="nav-link" href="notices.html"><span class="nav-icon">!</span>Notices</a><a class="nav-link" href="#" onclick="logout(event)"><span class="nav-icon">↪</span>Sign Out</a></div>`;const rolePill=document.getElementById("rolePill");if(rolePill)rolePill.textContent=d.label;const name=document.getElementById("userName");if(name)name.textContent=d.name;const avatar=document.getElementById("userAvatar");if(avatar)avatar.textContent=d.avatar}
function toggleSidebar(){document.getElementById("sidebar")?.classList.toggle("open")}
function toast(msg){const t=document.getElementById("toast");if(!t)return;t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function showAction(msg){toast(msg)}
function goSearch(){const q=document.getElementById("quickSearch")?.value.trim();location.href="catalog.html"+(q?"?q="+encodeURIComponent(q):"")}
document.addEventListener("DOMContentLoaded",()=>{if(guardRoute())renderSidebar()})
